/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  content: ["./index.html", "./**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#c284ff",
        "inverse-on-surface": "#53555a",
        "surface-tint": "#cc97ff",
        "surface-container-lowest": "#000000",
        "primary-dim": "#9c48ea",
        "secondary-fixed-dim": "#58e7ab",
        "on-surface-variant": "#aaabb0",
        "surface-bright": "#292c33",
        "on-primary-container": "#360061",
        "on-error": "#490013",
        "outline-variant": "#46484d",
        "secondary-container": "#006c49",
        "on-secondary-container": "#e1ffec",
        "on-primary": "#47007c",
        "on-tertiary": "#680921",
        "surface-container-high": "#1d2025",
        "surface-container-highest": "#23262c",
        "on-tertiary-fixed": "#39000d",
        "surface-container": "#171a1f",
        "inverse-surface": "#f9f9ff",
        "secondary-dim": "#58e7ab",
        "surface-container-low": "#111318",
        "tertiary-container": "#fe7e8e",
        "on-background": "#f6f6fc",
        "on-error-container": "#ffb2b9",
        "secondary-fixed": "#69f6b8",
        "surface-variant": "#23262c",
        "surface-dim": "#0c0e12",
        "on-surface": "#f6f6fc",
        outline: "#74757a",
        "tertiary-fixed-dim": "#fa7c8b",
        "on-tertiary-container": "#570018",
        secondary: "#69f6b8",
        "on-secondary-fixed": "#00452d",
        "on-tertiary-fixed-variant": "#711227",
        surface: "#0c0e12",
        "error-dim": "#d73357",
        error: "#ff6e84",
        "on-secondary": "#005a3c",
        "error-container": "#a70138",
        "tertiary-fixed": "#ff909c",
        "tertiary-dim": "#f47786",
        "on-primary-fixed-variant": "#430076",
        "primary-container": "#c284ff",
        "on-secondary-fixed-variant": "#006544",
        tertiary: "#ff95a0",
        "on-primary-fixed": "#000000",
        "inverse-primary": "#842cd3",
        background: "#0c0e12",
        "primary-fixed-dim": "#b971ff",
        primary: "#cc97ff",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}